# Source: https://dotnetcore.gaprogman.com/2017/06/08/continuous-integration-and-appveyor/
version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - cmd: choco install resharper-clt
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Matrix.SynapseInterop.sln --verbosity m
build_script:
  # output will be in ./{proj}/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./Matrix.SynapseInterop.sln
# Source: https://gist.github.com/IlyaFinkelshteyn/ec95c1cc06b304db1972659cabd22ff8
after_build:
  - cmd: InspectCode.exe -o=resharper-clt-output.xml ./Matrix.SynapseInterop.sln
  - ps: $result = [xml](Get-Content ./resharper-clt-output.xml)
  - ps: $result.Report.Issues.ChildNodes | ForEach-Object {$project = $_.Name; $_.ChildNodes | ForEach-Object {Add-AppveyorCompilationMessage -Message $_.Message -Line $_.Line -FileName $_.File -ProjectName $project}}
# TODO: Actual output executables
#artifacts:
# - path: '\src\bin\Debug\netcoreapp1.1\publish'
#   name: WebSite
#   type: WebDeployPackage
clone_depth: 1
# TODO: Tests
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off